services:

  frontend:
    build: ./Frontend

    ports:
      - "4000:4000"

    volumes:
      - ./Frontend:/app
      - /app/node_modules

    command: npm run dev

    environment:
      PORT: 4000

    depends_on:
      - backend

  backend:
    build: ./Backend

    ports:
      - "3000:3000"

    volumes:
      - ./Backend:/app
      - /app/node_modules

    command: npm run dev

    env_file:
      - ./Backend/.env

    depends_on:
      - mysql

  mysql:
    image: mysql:8

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: f8lnxf8l
      MYSQL_DATABASE: mce_celulares

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: